spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: yang
    username: root
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false




mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
